<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inbox</name>
   <tag></tag>
   <elementGuidId>2bd5828d-af8f-45b5-9341-140489ae3338</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>${index}</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>${index}</value>
   </webElementProperties>
</WebElementEntity>
