<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titLe</name>
   <tag></tag>
   <elementGuidId>48246c5f-f928-40d9-91d9-3230866cf06f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>${index}</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>${index}</value>
   </webElementProperties>
</WebElementEntity>
