<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_NextPage</name>
   <tag></tag>
   <elementGuidId>dbe9300b-57f5-46f3-90ea-e8dbdf00cb1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;document-viewer-content&quot;]/div[1]/div[2]/div[1]/div[1]/div[2]/div/div[3]/div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
