<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Last_Page</name>
   <tag></tag>
   <elementGuidId>bc91fd1d-0a9f-4ae3-b2a4-92e030f26719</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;document-viewer-content&quot;]/div[1]/div[2]/div[1]/div[1]/div[2]/div/div[3]/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
