<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ValueLastPage</name>
   <tag></tag>
   <elementGuidId>e8f17765-b6ed-42fb-9cc7-237300f3501e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;document-viewer-content&quot;]/div[1]/div[2]/div[1]/div[1]/div[2]/div/div[2]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
