<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Configuration_par_defaut</name>
   <tag></tag>
   <elementGuidId>47eed926-62a7-4fbe-820f-0f8e02099a24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;backOffice-dashboard&quot;]/div[3]/md-fab-speed-dial/md-fab-actions/div[1]/button/md-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
