<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_configuration</name>
   <tag></tag>
   <elementGuidId>1caf819d-f8c1-4e13-b35b-04c3b5a590f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;backOffice-dashboard&quot;]/div[3]/md-fab-speed-dial/md-fab-trigger/button/md-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
