<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Repertoire_cible</name>
   <tag></tag>
   <elementGuidId>4aecb42c-ff3c-4fa3-ba45-dbf4c112b7e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>${linkPath}</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>${linkPath}</value>
   </webElementProperties>
</WebElementEntity>
