<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Autorisations</name>
   <tag></tag>
   <elementGuidId>403222ee-738d-4745-a588-67754fc0a4ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'backoffice-admin-Dashboard']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;backoffice-admin-Dashboard&quot;]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;backoffice-admin-Dashboard&quot;]/div/button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>backoffice-admin-Dashboard</value>
   </webElementProperties>
</WebElementEntity>
