<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_retour</name>
   <tag></tag>
   <elementGuidId>58a38a46-0ab3-4505-af81-7e3abc6448db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;brazil-backoffice-administration-editInbox&quot;]/md-toolbar/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;brazil-backoffice-administration-editInbox&quot;]/md-toolbar/button[1]</value>
   </webElementProperties>
</WebElementEntity>
