<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>commentaire_vesion</name>
   <tag></tag>
   <elementGuidId>dd0e05a2-1fb0-4789-89e7-620b8def3e37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>${index}</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>${index}</value>
   </webElementProperties>
</WebElementEntity>
