<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>case_cocher</name>
   <tag></tag>
   <elementGuidId>510fdaf0-1a86-4771-b316-25b76e4eb08c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;dialogContent_casefile-action-dialog-set-acl&quot;]/rights-management/div/div[2]/div[2]/div[2]/div/div/div[1]/div[${index}]/div/div[1]/div[2]/md-checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;dialogContent_casefile-action-dialog-set-acl&quot;]/rights-management/div/div[2]/div[2]/div[2]/div/div/div[1]/div[${index}]/div/div[1]/div[2]/md-checkbox</value>
   </webElementProperties>
</WebElementEntity>
