<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>liste_utilisateur</name>
   <tag></tag>
   <elementGuidId>9d5fcad2-2ccf-40f0-be75-d2145aed76d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;dialogContent_casefile-action-dialog-set-acl&quot;]/rights-management/div/div[1]/div[1]/md-autocomplete/md-autocomplete-wrap/md-input-container/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;dialogContent_casefile-action-dialog-set-acl&quot;]/rights-management/div/div[1]/div[1]/md-autocomplete/md-autocomplete-wrap/md-input-container/input</value>
   </webElementProperties>
</WebElementEntity>
