<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>liste_utilisateur_bannette-DeleteUser</name>
   <tag></tag>
   <elementGuidId>d548f0a2-0605-4218-a1c9-34d43b5a1845</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;dialogContent_casefile-action-dialog-set-acl&quot;]/rights-management/div/div[2]/div[${numLine}]/div[2]/div/div/div[2]/button/md-icon</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
