<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>liste_utilisateur_bannette</name>
   <tag></tag>
   <elementGuidId>4c07febf-682e-4883-ba14-42e089dcb9c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;dialogContent_casefile-action-dialog-set-acl&quot;]/rights-management/div/div[2]/div[${numLine}]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
