<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Xpath</name>
   <tag></tag>
   <elementGuidId>79bd9015-865c-472b-a9ef-cabb90f1397b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>${index}</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
