<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>__input-tag</name>
   <tag></tag>
   <elementGuidId>faaa55d2-7424-47bd-b543-77c9985ecbf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;edit-inbox-tab-color-ged-container&quot;]/md-list/md-list-item[1]/md-input-container/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;edit-inbox-tab-color-ged-container&quot;]/md-list/md-list-item[1]/md-input-container/label</value>
   </webElementProperties>
</WebElementEntity>
