<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_confirmation_suppression</name>
   <tag></tag>
   <elementGuidId>4b46fe52-b107-4440-b6d6-831fb0c1068f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/md-dialog/md-dialog-actions/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/md-dialog/md-dialog-actions/button[2]</value>
   </webElementProperties>
</WebElementEntity>
