<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Enlever_Element</name>
   <tag></tag>
   <elementGuidId>bfdbd422-6cef-4582-a335-495bcc8e2fe1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[5]/div/div/div/div[3]/div[2]/section/md-content/inbox-view[5]/section[3]/md-content/div[1]/md-button-circular-progress/button/md-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[5]/div/div/div/div[3]/div[2]/section/md-content/inbox-view[5]/section[3]/md-content/div[1]/md-button-circular-progress/button/md-icon</value>
   </webElementProperties>
</WebElementEntity>
