<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PremireBannette</name>
   <tag></tag>
   <elementGuidId>5490ab3d-7930-4e24-b8a0-540a6f062fa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[28]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@type = 'button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.md-no-style.md-button.md-default-theme.md-ink-ripple</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-no-style md-button md-default-theme md-ink-ripple</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>display.setInboxProperties(inbox,$event)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>GED</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-inbox-left-panel-container&quot;)/section[2]/md-list[@class=&quot;scrollBarStyle md-default-theme&quot;]/div[1]/md-list-item[@class=&quot;md-1-line md-primary _md-button-wrap _md md-clickable&quot;]/div[@class=&quot;md-button md-no-style&quot;]/button[@class=&quot;md-no-style md-button md-default-theme md-ink-ripple&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[27ububbi]</value>
   </webElementXpaths>
</WebElementEntity>
