<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DosseirInBan</name>
   <tag></tag>
   <elementGuidId>04fa4bb3-bb96-4bcd-a29b-d758060c5ba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>${index}</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;${index}&quot;]/md-content/div[${num}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>${index}</value>
   </webElementProperties>
</WebElementEntity>
