<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ListContenuBannette</name>
   <tag></tag>
   <elementGuidId>64034260-ec84-4e43-89bd-e871e76d01f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>${index}</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;${index}&quot;]/md-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>${index}</value>
   </webElementProperties>
</WebElementEntity>
