<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search_bannette</name>
   <tag></tag>
   <elementGuidId>386d649c-378f-4f26-ae2c-5e162498d2c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;edit-inbox-left-panel-container&quot;]/section[2]/md-input-container/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;edit-inbox-left-panel-container&quot;]/section[2]/md-input-container/input</value>
   </webElementProperties>
</WebElementEntity>
