<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tags_text</name>
   <tag></tag>
   <elementGuidId>b3a4affb-0acb-45e8-84ca-7ab4396beea0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;edit-inbox-content-edit-properties-container&quot;]/article[${index}]/md-input-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;edit-inbox-content-edit-properties-container&quot;]/article[${index}]/md-input-container</value>
   </webElementProperties>
</WebElementEntity>
