<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Trois_button_clickable</name>
   <tag></tag>
   <elementGuidId>6f46b196-7932-40d2-9232-cf7ea056fce8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;brazil-backoffice-administration-editInbox&quot;]/md-toolbar/button[${index}]/md-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;brazil-backoffice-administration-editInbox&quot;]/md-toolbar/button[${index}]/md-icon</value>
   </webElementProperties>
</WebElementEntity>
