<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Aide_idd</name>
   <tag></tag>
   <elementGuidId>412261c7-ef3a-449f-9a2b-be6f5af7709e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;idd&quot;)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idd</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!loading</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>https://doxtreem-uat2.numen.solutions/deck/oauthCallback.html#access_token=eyJ4NXQiOiJNR00zTjJZeU5EVmtZalF4WXpFMU5EazROVFl6WTJNd01tWTRaalJpTlRRM04yTmhOV1ExWTJSak1HTTJaVGcwTTJWak1qQmhaVE0xTm1NellUZzNNQSIsImtpZCI6Ik1HTTNOMll5TkRWa1lqUXhZekUxTkRrNE5UWXpZMk13TW1ZNFpqUmlOVFEzTjJOaE5XUTFZMlJqTUdNMlpUZzBNMlZqTWpCaFpUTTFObU16WVRnM01BX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJEWF9hZG1pbiIsImlzcyI6Imh0dHBzOlwvXC9kb3h0cmVlbS13c28yLXVhdDIubnVtZW4uc29sdXRpb25zOjQ0M1wvb2F1dGgyXC90b2tlbiIsImdyb3VwcyI6WyJHcm91cGUtV2ViREFWIiwiSW50ZXJuYWxcL2V2ZXJ5b25lIl0sImdpdmVuX25hbWUiOiJEWF9hZG1pbiIsImF1ZCI6IlRESFlkY0hlb1ppYTZ0YXdXY29TRks3IiwidXBuIjoiRFhfYWRtaW4iLCJuYmYiOjE2MTM0NjI2NTQsImF6cCI6IlRESFlkY0hlb1ppYTZ0YXdXY29TRks3Iiwic2NvcGUiOiJpbnRlcm5hbF9sb2dpbiBvcGVuaWQiLCJleHAiOjE2MTM0NjYyNTQsImlhdCI6MTYxMzQ2MjY1NCwiZmFtaWx5X25hbWUiOiJEWF9hZG1pbiIsImp0aSI6ImY0MGI4NDA4LWM2OWItNDhhYS1iMzkwLWVkNDE2NmQ2MTliOSIsImVtYWlsIjoiZGV2QG51bWVuLmZyIn0.bvqwESFQw0snlIi2joZw1JvTmLBZ4HHyrE3QvsLYupRyKecxVHm3bTu2v3muLn8TdEtmQAMMPWDfhrpx-UZ3_eEezO48a6wfpYLij5Oi02hxYeXAkcx62yH7XPaSHTnG4XYlAFGoYVhYKOBctu6ySGcKXQ-3S5BBeCxHhAx6UtuZSf5NvY7OTW7FPp-_Vs7f2YfPV7RXsj4aot9gU4Ro4HOF7V26JKrRt8FI9toTO_A_9zAHe9OHjoR5FVvaPXo9SBAR552MGdBguvKi6m48OC-aWoAg7hngjHN2-WWF-tsTrQZ_b_Oz1rJNNXOwbMKp66vqA1tJUJ06eORFqxncoQ&amp;expires_in=0&amp;state=NB2HI4DTHIXS6ZDPPB2HEZLFNUWXKYLUGIXG45LNMVXC443PNR2XI2LPNZZS6ZDFMNVS65LBOQZGOYZPOVZWK4TT</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>99%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://doxtreem-uat2.numen.solutions/deck/oauthCallback.html#access_token=eyJ4NXQiOiJNR00zTjJZeU5EVmtZalF4WXpFMU5EazROVFl6WTJNd01tWTRaalJpTlRRM04yTmhOV1ExWTJSak1HTTJaVGcwTTJWak1qQmhaVE0xTm1NellUZzNNQSIsImtpZCI6Ik1HTTNOMll5TkRWa1lqUXhZekUxTkRrNE5UWXpZMk13TW1ZNFpqUmlOVFEzTjJOaE5XUTFZMlJqTUdNMlpUZzBNMlZqTWpCaFpUTTFObU16WVRnM01BX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJEWF9hZG1pbiIsImlzcyI6Imh0dHBzOlwvXC9kb3h0cmVlbS13c28yLXVhdDIubnVtZW4uc29sdXRpb25zOjQ0M1wvb2F1dGgyXC90b2tlbiIsImdyb3VwcyI6WyJHcm91cGUtV2ViREFWIiwiSW50ZXJuYWxcL2V2ZXJ5b25lIl0sImdpdmVuX25hbWUiOiJEWF9hZG1pbiIsImF1ZCI6IlRESFlkY0hlb1ppYTZ0YXdXY29TRks3IiwidXBuIjoiRFhfYWRtaW4iLCJuYmYiOjE2MTM0NjI2NTQsImF6cCI6IlRESFlkY0hlb1ppYTZ0YXdXY29TRks3Iiwic2NvcGUiOiJpbnRlcm5hbF9sb2dpbiBvcGVuaWQiLCJleHAiOjE2MTM0NjYyNTQsImlhdCI6MTYxMzQ2MjY1NCwiZmFtaWx5X25hbWUiOiJEWF9hZG1pbiIsImp0aSI6ImY0MGI4NDA4LWM2OWItNDhhYS1iMzkwLWVkNDE2NmQ2MTliOSIsImVtYWlsIjoiZGV2QG51bWVuLmZyIn0.bvqwESFQw0snlIi2joZw1JvTmLBZ4HHyrE3QvsLYupRyKecxVHm3bTu2v3muLn8TdEtmQAMMPWDfhrpx-UZ3_eEezO48a6wfpYLij5Oi02hxYeXAkcx62yH7XPaSHTnG4XYlAFGoYVhYKOBctu6ySGcKXQ-3S5BBeCxHhAx6UtuZSf5NvY7OTW7FPp-_Vs7f2YfPV7RXsj4aot9gU4Ro4HOF7V26JKrRt8FI9toTO_A_9zAHe9OHjoR5FVvaPXo9SBAR552MGdBguvKi6m48OC-aWoAg7hngjHN2-WWF-tsTrQZ_b_Oz1rJNNXOwbMKp66vqA1tJUJ06eORFqxncoQ&amp;expires_in=0&amp;state=NB2HI4DTHIXS6ZDPPB2HEZLFNUWXKYLUGIXG45LNMVXC443PNR2XI2LPNZZS6ZDFMNVS65LBOQZGOYZPOVZWK4TT</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cd_frame_id_</name>
      <type>Main</type>
      <value>67f83d0ab2ac9485a3a2dee882faa883</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idd&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='idd']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='template-module']/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
   </webElementXpaths>
</WebElementEntity>
