<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MenuUtilisateurs</name>
   <tag></tag>
   <elementGuidId>29cc13f7-ba4c-444b-a3c0-977764adfca2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/div/nav/div[2]/div/div/a[1]/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/div/nav/div[2]/div/div/a[1]/mat-icon</value>
   </webElementProperties>
</WebElementEntity>
