<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_Rercherche_Contextuelle</name>
   <tag></tag>
   <elementGuidId>15e541e7-bff6-4b54-918a-e0d7dbd584a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[starts-with(@id,&quot;tab-content-&quot;)]/div/md-content/div/div/div[1]/md-switch/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
