<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_Information</name>
   <tag></tag>
   <elementGuidId>ddf7e3eb-d68c-4d1e-9819-72cb63c018ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//md-icon[@md-svg-icon='mdi:information']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
