<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_download_zip</name>
   <tag></tag>
   <elementGuidId>08045db9-2f53-40eb-8c0a-d1c7971dbc02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;inboxExplorerDisplayList&quot;]/div[3]/div[2]/div/div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//*[@id=&quot;inboxExplorerDisplayList&quot;]/div[3]/div[2]/div/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
