<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Nouveau_Dossier_Barre_horizontale</name>
   <tag></tag>
   <elementGuidId>d1aa4195-03e5-43cc-ac3b-02caf542f197</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//md-icon[@md-svg-icon='mdi:folder-plus']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;topButton&quot;]/button//md-icon[@md-svg-icon=&quot;mdi:folder-plus&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;topButton&quot;]/button//md-icon[@md-svg-icon=&quot;mdi:folder-plus&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topButton']/button/md-icon</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//md-menu/div/button/md-icon</value>
   </webElementXpaths>
</WebElementEntity>
