<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_validation_supp_doc</name>
   <tag></tag>
   <elementGuidId>e847df1e-8bb6-4e22-af9a-0099c2aedd69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[${index}]/md-dialog/form/md-dialog-actions[2]/button[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[${index}]/md-dialog/form/md-dialog-actions[2]/button[3]</value>
   </webElementProperties>
</WebElementEntity>
