<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_deleteAllFavoris</name>
   <tag></tag>
   <elementGuidId>5bace757-b042-431a-adf3-b4f07dbafaf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body/div[@id='${index}']/md-menu-content[1]/md-menu-item[3]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body/div[@id='${index}']/md-menu-content[1]/md-menu-item[3]/button[1]</value>
   </webElementProperties>
</WebElementEntity>
