<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ReinitialiserGlobal</name>
   <tag></tag>
   <elementGuidId>50bf23a3-ff6f-4aab-a367-0b87ed35057f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@class = 'md-raised md-warn md-button md-default-theme md-ink-ripple' and @type = 'button' and (text() = 'Réinitialiser' or . = 'Réinitialiser') and @ng-click = 'onGlobalFilterReinit()']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;inboxes-global-global-filters-container&quot;]//button[normalize-space()='Réinitialiser']
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-raised md-warn md-button md-default-theme md-ink-ripple</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Réinitialiser</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>onGlobalFilterReinit()</value>
   </webElementProperties>
</WebElementEntity>
