<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dossier_a_cliquer</name>
   <tag></tag>
   <elementGuidId>77543f76-13df-4b02-8c71-d40cb89c80fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;inboxExplorerList&quot;]/div[${index}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;inboxExplorerList&quot;]/div[${index}]</value>
   </webElementProperties>
</WebElementEntity>
