<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fenetre_ajoutDroitsUtilisateurs</name>
   <tag></tag>
   <elementGuidId>4e3724dc-2119-4f76-81b6-1816fd31ec09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;casefile-action-dialog-set-acl&quot;]/md-toolbar/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;casefile-action-dialog-set-acl&quot;]/md-toolbar/div</value>
   </webElementProperties>
</WebElementEntity>
