<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_etoile_favoris</name>
   <tag></tag>
   <elementGuidId>037ed671-c2e3-425e-9310-0daeff461e13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='inboxExplorerList']/div/div/md-menu/div/div/div[1]/div[3]/div[1]/div/span/md-icon</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
