<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nom_fichier_chemin-de-fer</name>
   <tag></tag>
   <elementGuidId>a731dc6a-5063-4795-8ed7-c3c38fe1a7b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;breadcrumb-directive&quot;]/div[3]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;breadcrumb-directive&quot;]/div[3]/div/span</value>
   </webElementProperties>
</WebElementEntity>
