<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Onglet_Details</name>
   <tag></tag>
   <elementGuidId>f7da3046-9231-437c-b8e7-a4088a5c560e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//md-tab-item[starts-with(@id,'tab-item-')]//span[@class='flex'][normalize-space()='Détails']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
