<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>resultat_utilisateurSelectionné</name>
   <tag></tag>
   <elementGuidId>4a4699e6-45ba-413a-a7e7-26fcf5b1b493</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[starts-with(@id,&quot;ul-&quot;)]/li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[starts-with(@id,&quot;ul-&quot;)]/li[1]</value>
   </webElementProperties>
</WebElementEntity>
