<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tableau_ListeDossier</name>
   <tag></tag>
   <elementGuidId>a230c506-6f03-4843-8d7f-06aa6b41eae0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;inboxExplorerDisplayList&quot;]/div[3]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;inboxExplorerDisplayList&quot;]/div[3]/div[2]</value>
   </webElementProperties>
</WebElementEntity>
