<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Valider_action</name>
   <tag></tag>
   <elementGuidId>123faf9a-0769-412a-92c8-eeba0a6ecaeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[${index}]/md-dialog/form/md-dialog-actions[2]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[${index}]/md-dialog/form/md-dialog-actions[2]/button[2]</value>
   </webElementProperties>
</WebElementEntity>
