<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Aide_idd</name>
   <tag></tag>
   <elementGuidId>0f9a2bb0-f943-43e3-95d1-debdf7070d71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='idd']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'idd' and @src = 'https://doxtreem-uat2.numen.solutions/deck/oauthCallback.html#access_token=eyJ4NXQiOiJNR00zTjJZeU5EVmtZalF4WXpFMU5EazROVFl6WTJNd01tWTRaalJpTlRRM04yTmhOV1ExWTJSak1HTTJaVGcwTTJWak1qQmhaVE0xTm1NellUZzNNQSIsImtpZCI6Ik1HTTNOMll5TkRWa1lqUXhZekUxTkRrNE5UWXpZMk13TW1ZNFpqUmlOVFEzTjJOaE5XUTFZMlJqTUdNMlpUZzBNMlZqTWpCaFpUTTFObU16WVRnM01BX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJEWF9hZG1pbiIsImlzcyI6Imh0dHBzOlwvXC9kb3h0cmVlbS13c28yLXVhdDIubnVtZW4uc29sdXRpb25zOjQ0M1wvb2F1dGgyXC90b2tlbiIsImdyb3VwcyI6WyJHcm91cGUtV2ViREFWIiwiSW50ZXJuYWxcL2V2ZXJ5b25lIl0sImdpdmVuX25hbWUiOiJEWF9hZG1pbiIsImF1ZCI6IlRESFlkY0hlb1ppYTZ0YXdXY29TRks3IiwidXBuIjoiRFhfYWRtaW4iLCJuYmYiOjE2MTM2NDM4NTMsImF6cCI6IlRESFlkY0hlb1ppYTZ0YXdXY29TRks3Iiwic2NvcGUiOiJpbnRlcm5hbF9sb2dpbiBvcGVuaWQiLCJleHAiOjE2MTM2NDc0NTMsImlhdCI6MTYxMzY0Mzg1MywiZmFtaWx5X25hbWUiOiJEWF9hZG1pbiIsImp0aSI6IjgyZDZmMGY1LTI5YmQtNDM4NC04MGI0LTA2YzU5ZjNlZTg0YSIsImVtYWlsIjoiZGV2QG51bWVuLmZyIn0.jawyj8n919n2KHfBPoEZUO4sdx638UW08GVxELXw4A-BBrcNXRh3eKJw7wB8n7sOwPeSkwj0Q22ZUcGxz_oaRdJpYwl827LJ45K-p1_EhSUWPKyM23fOdMixBqT-V_6fapfEMF6ZFswMGULpv_9c5GWkydLrgAdfnDRsax6pfUx5RYw0xLmsPaQDO84MVSr9Yabugat2I6-G04J-yGofbp3YHnZkBk3gjGccgibsqxKme3XhYNafY76TcV9zNhoZ3k0RCfs3pnzQOHR1vhwO1BqM4k21W8rDKM6QOGDKhDNYcsH0gCpcEj1FvoyIH4QiD88oaGcsp7b0QTEkhNLr6Q&amp;expires_in=0&amp;state=NB2HI4DTHIXS6ZDPPB2HEZLFNUWXKYLUGIXG45LNMVXC443PNR2XI2LPNZZS6ZDFMNVS65LBOQZGOYZPNBQWE2LMNF2GC5DJN5XHG===']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idd</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!loading</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>https://doxtreem-uat2.numen.solutions/deck/oauthCallback.html#access_token=eyJ4NXQiOiJNR00zTjJZeU5EVmtZalF4WXpFMU5EazROVFl6WTJNd01tWTRaalJpTlRRM04yTmhOV1ExWTJSak1HTTJaVGcwTTJWak1qQmhaVE0xTm1NellUZzNNQSIsImtpZCI6Ik1HTTNOMll5TkRWa1lqUXhZekUxTkRrNE5UWXpZMk13TW1ZNFpqUmlOVFEzTjJOaE5XUTFZMlJqTUdNMlpUZzBNMlZqTWpCaFpUTTFObU16WVRnM01BX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJEWF9hZG1pbiIsImlzcyI6Imh0dHBzOlwvXC9kb3h0cmVlbS13c28yLXVhdDIubnVtZW4uc29sdXRpb25zOjQ0M1wvb2F1dGgyXC90b2tlbiIsImdyb3VwcyI6WyJHcm91cGUtV2ViREFWIiwiSW50ZXJuYWxcL2V2ZXJ5b25lIl0sImdpdmVuX25hbWUiOiJEWF9hZG1pbiIsImF1ZCI6IlRESFlkY0hlb1ppYTZ0YXdXY29TRks3IiwidXBuIjoiRFhfYWRtaW4iLCJuYmYiOjE2MTM2NDM4NTMsImF6cCI6IlRESFlkY0hlb1ppYTZ0YXdXY29TRks3Iiwic2NvcGUiOiJpbnRlcm5hbF9sb2dpbiBvcGVuaWQiLCJleHAiOjE2MTM2NDc0NTMsImlhdCI6MTYxMzY0Mzg1MywiZmFtaWx5X25hbWUiOiJEWF9hZG1pbiIsImp0aSI6IjgyZDZmMGY1LTI5YmQtNDM4NC04MGI0LTA2YzU5ZjNlZTg0YSIsImVtYWlsIjoiZGV2QG51bWVuLmZyIn0.jawyj8n919n2KHfBPoEZUO4sdx638UW08GVxELXw4A-BBrcNXRh3eKJw7wB8n7sOwPeSkwj0Q22ZUcGxz_oaRdJpYwl827LJ45K-p1_EhSUWPKyM23fOdMixBqT-V_6fapfEMF6ZFswMGULpv_9c5GWkydLrgAdfnDRsax6pfUx5RYw0xLmsPaQDO84MVSr9Yabugat2I6-G04J-yGofbp3YHnZkBk3gjGccgibsqxKme3XhYNafY76TcV9zNhoZ3k0RCfs3pnzQOHR1vhwO1BqM4k21W8rDKM6QOGDKhDNYcsH0gCpcEj1FvoyIH4QiD88oaGcsp7b0QTEkhNLr6Q&amp;expires_in=0&amp;state=NB2HI4DTHIXS6ZDPPB2HEZLFNUWXKYLUGIXG45LNMVXC443PNR2XI2LPNZZS6ZDFMNVS65LBOQZGOYZPNBQWE2LMNF2GC5DJN5XHG===</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>99%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://doxtreem-uat2.numen.solutions/deck/oauthCallback.html#access_token=eyJ4NXQiOiJNR00zTjJZeU5EVmtZalF4WXpFMU5EazROVFl6WTJNd01tWTRaalJpTlRRM04yTmhOV1ExWTJSak1HTTJaVGcwTTJWak1qQmhaVE0xTm1NellUZzNNQSIsImtpZCI6Ik1HTTNOMll5TkRWa1lqUXhZekUxTkRrNE5UWXpZMk13TW1ZNFpqUmlOVFEzTjJOaE5XUTFZMlJqTUdNMlpUZzBNMlZqTWpCaFpUTTFObU16WVRnM01BX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJEWF9hZG1pbiIsImlzcyI6Imh0dHBzOlwvXC9kb3h0cmVlbS13c28yLXVhdDIubnVtZW4uc29sdXRpb25zOjQ0M1wvb2F1dGgyXC90b2tlbiIsImdyb3VwcyI6WyJHcm91cGUtV2ViREFWIiwiSW50ZXJuYWxcL2V2ZXJ5b25lIl0sImdpdmVuX25hbWUiOiJEWF9hZG1pbiIsImF1ZCI6IlRESFlkY0hlb1ppYTZ0YXdXY29TRks3IiwidXBuIjoiRFhfYWRtaW4iLCJuYmYiOjE2MTM2NDM4NTMsImF6cCI6IlRESFlkY0hlb1ppYTZ0YXdXY29TRks3Iiwic2NvcGUiOiJpbnRlcm5hbF9sb2dpbiBvcGVuaWQiLCJleHAiOjE2MTM2NDc0NTMsImlhdCI6MTYxMzY0Mzg1MywiZmFtaWx5X25hbWUiOiJEWF9hZG1pbiIsImp0aSI6IjgyZDZmMGY1LTI5YmQtNDM4NC04MGI0LTA2YzU5ZjNlZTg0YSIsImVtYWlsIjoiZGV2QG51bWVuLmZyIn0.jawyj8n919n2KHfBPoEZUO4sdx638UW08GVxELXw4A-BBrcNXRh3eKJw7wB8n7sOwPeSkwj0Q22ZUcGxz_oaRdJpYwl827LJ45K-p1_EhSUWPKyM23fOdMixBqT-V_6fapfEMF6ZFswMGULpv_9c5GWkydLrgAdfnDRsax6pfUx5RYw0xLmsPaQDO84MVSr9Yabugat2I6-G04J-yGofbp3YHnZkBk3gjGccgibsqxKme3XhYNafY76TcV9zNhoZ3k0RCfs3pnzQOHR1vhwO1BqM4k21W8rDKM6QOGDKhDNYcsH0gCpcEj1FvoyIH4QiD88oaGcsp7b0QTEkhNLr6Q&amp;expires_in=0&amp;state=NB2HI4DTHIXS6ZDPPB2HEZLFNUWXKYLUGIXG45LNMVXC443PNR2XI2LPNZZS6ZDFMNVS65LBOQZGOYZPNBQWE2LMNF2GC5DJN5XHG===</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idd&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='idd']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='template-module']/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
   </webElementXpaths>
</WebElementEntity>
