<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Champ_Nom_parametrage_nouveau_dossier</name>
   <tag></tag>
   <elementGuidId>f921f2d8-8316-453c-a4ac-1d85c5c90025</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;tab-content-1408&quot;)/div[1]/ng-form[@class=&quot;ng-pristine ng-valid ng-valid-required ng-valid-pattern layout-column&quot;]/div[@class=&quot;layout-column&quot;]/md-input-container[@class=&quot;md-icon-right md-default-theme md-input-has-value layout-row md-input-focused&quot;]/input[@class=&quot;ng-pristine ng-untouched ng-valid md-input ng-not-empty ng-valid-required ng-valid-pattern&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ng-form/div[1]/md-input-container/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>field.type === 'text'</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>field.required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>field.readOnly || isReadOnly</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>formProperties[field.propertyId]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-id</name>
      <type>Main</type>
      <value>{{field.propertyId === 'labelRegex' ? 'regexInputToCopy': ''}}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid md-input ng-not-empty ng-valid-required ng-valid-pattern</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-content-1408&quot;)/div[1]/ng-form[@class=&quot;ng-pristine ng-valid ng-valid-required ng-valid-pattern layout-column&quot;]/div[@class=&quot;layout-column&quot;]/md-input-container[@class=&quot;md-icon-right md-default-theme md-input-has-value layout-row md-input-focused&quot;]/input[@class=&quot;ng-pristine ng-untouched ng-valid md-input ng-not-empty ng-valid-required ng-valid-pattern&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//md-tab-content[@id='tab-content-1408']/div/ng-form/div/md-input-container/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-form/div/md-input-container/input</value>
   </webElementXpaths>
</WebElementEntity>
