<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>md-tab-content</name>
   <tag></tag>
   <elementGuidId>bc7ee6a1-0ac8-4c77-b9cf-3add28c5a579</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;edit-base-type-infos&quot;]/md-tabs/md-tabs-content-wrapper/md-tab-content[${index}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;edit-base-type-infos&quot;]/md-tabs/md-tabs-content-wrapper/md-tab-content[${index}]</value>
   </webElementProperties>
</WebElementEntity>
