<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_suppr_user</name>
   <tag></tag>
   <elementGuidId>b2c74326-a54d-4ebc-a5a9-5b7de24b4e4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;usertable&quot;]/mat-row/mat-cell[5]/button[4]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;usertable&quot;]/mat-row[1]/mat-cell[4]/button[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;usertable&quot;]/mat-row[1]/mat-cell[4]/button[4]</value>
   </webElementProperties>
</WebElementEntity>
