<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_suppr_DX_Admin</name>
   <tag></tag>
   <elementGuidId>5a3bf719-cce9-4758-9f78-c03d3a9bc8c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/div/app-is-users/div/div/mat-table/mat-row/mat-cell[5]/button[4]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/div/app-is-users/div/div/mat-table/mat-row/mat-cell[4]/button[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/div/app-is-users/div/div/mat-table/mat-row/mat-cell[4]/button[4]</value>
   </webElementProperties>
</WebElementEntity>
