<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icone_role_grp</name>
   <tag></tag>
   <elementGuidId>6363abd2-9ee0-4b98-b9c2-7acb7c737ba2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div[2]/div/mat-dialog-container/app-is-user-dialog/div[1]/mat-tab-group/mat-tab-header/div[2]/div/div/div[3]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'roles')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div[2]/div/mat-dialog-container/app-is-user-dialog/div[1]/mat-tab-group/mat-tab-header/div[2]/div/div/div[3]</value>
   </webElementProperties>
</WebElementEntity>
