<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Aide_idd</name>
   <tag></tag>
   <elementGuidId>e8423fe7-5656-45d4-8dfd-7b1d62da8243</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idd</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!loading</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>https://doxtreem-uat2.numen.solutions/deck/oauthCallback.html#access_token=eyJ4NXQiOiJNR00zTjJZeU5EVmtZalF4WXpFMU5EazROVFl6WTJNd01tWTRaalJpTlRRM04yTmhOV1ExWTJSak1HTTJaVGcwTTJWak1qQmhaVE0xTm1NellUZzNNQSIsImtpZCI6Ik1HTTNOMll5TkRWa1lqUXhZekUxTkRrNE5UWXpZMk13TW1ZNFpqUmlOVFEzTjJOaE5XUTFZMlJqTUdNMlpUZzBNMlZqTWpCaFpUTTFObU16WVRnM01BX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJEWF9hZG1pbiIsImlzcyI6Imh0dHBzOlwvXC9kb3h0cmVlbS13c28yLXVhdDIubnVtZW4uc29sdXRpb25zOjQ0M1wvb2F1dGgyXC90b2tlbiIsImdyb3VwcyI6WyJHcm91cGUtV2ViREFWIiwiSW50ZXJuYWxcL2V2ZXJ5b25lIl0sImdpdmVuX25hbWUiOiJEWF9hZG1pbiIsImF1ZCI6IlRESFlkY0hlb1ppYTZ0YXdXY29TRks3IiwidXBuIjoiRFhfYWRtaW4iLCJuYmYiOjE2MTM3MjQ2MTksImF6cCI6IlRESFlkY0hlb1ppYTZ0YXdXY29TRks3Iiwic2NvcGUiOiJpbnRlcm5hbF9sb2dpbiBvcGVuaWQiLCJleHAiOjE2MTM3MjgyMTksImlhdCI6MTYxMzcyNDYxOSwiZmFtaWx5X25hbWUiOiJEWF9hZG1pbiIsImp0aSI6ImMzYWYyMTFkLTBjNzctNGUwYS1hYTMzLTA4NmE3ZjEyNzQ1YyIsImVtYWlsIjoiZGV2QG51bWVuLmZyIn0.CmJ4lApu13qXi4o1pqq5XN-6ywBMHE51JTfFVauybIZro1ugChVhDSQ9Fttk3PPoMaeXdSpYf71tpqiyFQu8RAX3jToHj_Sz-Y8IYsxiZxx_Qaf3D2BH_hhmSGjksEZYzljZHw53p0Tc3FvZG-f_3V25NR27w5yNxm5GmY-zkJ9YUSzVtoiKYcuWX-qQ4B3SIRt4oEK8w3040E83Xp1Oi4yeiKF5R9SBB8e0Gtt7Em4NJKBIjs-qpYMbXC43oG5_RUm07aC1EVI6BZA57vwgOY3YAGoroLc9rxwuhn1Zspzn65NDN3FDTLr_Ezs-2N5KKBZGJgygezb_9FEkkuPRmw&amp;expires_in=0&amp;state=NB2HI4DTHIXS6ZDPPB2HEZLFNUWXKYLUGIXG45LNMVXC443PNR2XI2LPNZZS6ZDFMNVS65LBOQZGOYZPM5ZG65LQOM======</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>99%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://doxtreem-uat2.numen.solutions/deck/oauthCallback.html#access_token=eyJ4NXQiOiJNR00zTjJZeU5EVmtZalF4WXpFMU5EazROVFl6WTJNd01tWTRaalJpTlRRM04yTmhOV1ExWTJSak1HTTJaVGcwTTJWak1qQmhaVE0xTm1NellUZzNNQSIsImtpZCI6Ik1HTTNOMll5TkRWa1lqUXhZekUxTkRrNE5UWXpZMk13TW1ZNFpqUmlOVFEzTjJOaE5XUTFZMlJqTUdNMlpUZzBNMlZqTWpCaFpUTTFObU16WVRnM01BX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJEWF9hZG1pbiIsImlzcyI6Imh0dHBzOlwvXC9kb3h0cmVlbS13c28yLXVhdDIubnVtZW4uc29sdXRpb25zOjQ0M1wvb2F1dGgyXC90b2tlbiIsImdyb3VwcyI6WyJHcm91cGUtV2ViREFWIiwiSW50ZXJuYWxcL2V2ZXJ5b25lIl0sImdpdmVuX25hbWUiOiJEWF9hZG1pbiIsImF1ZCI6IlRESFlkY0hlb1ppYTZ0YXdXY29TRks3IiwidXBuIjoiRFhfYWRtaW4iLCJuYmYiOjE2MTM3MjQ2MTksImF6cCI6IlRESFlkY0hlb1ppYTZ0YXdXY29TRks3Iiwic2NvcGUiOiJpbnRlcm5hbF9sb2dpbiBvcGVuaWQiLCJleHAiOjE2MTM3MjgyMTksImlhdCI6MTYxMzcyNDYxOSwiZmFtaWx5X25hbWUiOiJEWF9hZG1pbiIsImp0aSI6ImMzYWYyMTFkLTBjNzctNGUwYS1hYTMzLTA4NmE3ZjEyNzQ1YyIsImVtYWlsIjoiZGV2QG51bWVuLmZyIn0.CmJ4lApu13qXi4o1pqq5XN-6ywBMHE51JTfFVauybIZro1ugChVhDSQ9Fttk3PPoMaeXdSpYf71tpqiyFQu8RAX3jToHj_Sz-Y8IYsxiZxx_Qaf3D2BH_hhmSGjksEZYzljZHw53p0Tc3FvZG-f_3V25NR27w5yNxm5GmY-zkJ9YUSzVtoiKYcuWX-qQ4B3SIRt4oEK8w3040E83Xp1Oi4yeiKF5R9SBB8e0Gtt7Em4NJKBIjs-qpYMbXC43oG5_RUm07aC1EVI6BZA57vwgOY3YAGoroLc9rxwuhn1Zspzn65NDN3FDTLr_Ezs-2N5KKBZGJgygezb_9FEkkuPRmw&amp;expires_in=0&amp;state=NB2HI4DTHIXS6ZDPPB2HEZLFNUWXKYLUGIXG45LNMVXC443PNR2XI2LPNZZS6ZDFMNVS65LBOQZGOYZPM5ZG65LQOM======</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idd&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='idd']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='template-module']/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
   </webElementXpaths>
</WebElementEntity>
