<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Groupe</name>
   <tag></tag>
   <elementGuidId>48237e90-e819-4245-8769-ad5d6208ae3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='idd']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'idd' and @src = 'https://doxtreem-uat2.numen.solutions/deck/oauthCallback.html#access_token=eyJ4NXQiOiJNR00zTjJZeU5EVmtZalF4WXpFMU5EazROVFl6WTJNd01tWTRaalJpTlRRM04yTmhOV1ExWTJSak1HTTJaVGcwTTJWak1qQmhaVE0xTm1NellUZzNNQSIsImtpZCI6Ik1HTTNOMll5TkRWa1lqUXhZekUxTkRrNE5UWXpZMk13TW1ZNFpqUmlOVFEzTjJOaE5XUTFZMlJqTUdNMlpUZzBNMlZqTWpCaFpUTTFObU16WVRnM01BX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJEWF9hZG1pbiIsImlzcyI6Imh0dHBzOlwvXC9kb3h0cmVlbS13c28yLXVhdDIubnVtZW4uc29sdXRpb25zOjQ0M1wvb2F1dGgyXC90b2tlbiIsImdyb3VwcyI6WyJHcm91cGUtV2ViREFWIiwiSW50ZXJuYWxcL2V2ZXJ5b25lIl0sImdpdmVuX25hbWUiOiJEWF9hZG1pbiIsImF1ZCI6IlRESFlkY0hlb1ppYTZ0YXdXY29TRks3IiwidXBuIjoiRFhfYWRtaW4iLCJuYmYiOjE2MTM1NDEwMzYsImF6cCI6IlRESFlkY0hlb1ppYTZ0YXdXY29TRks3Iiwic2NvcGUiOiJpbnRlcm5hbF9sb2dpbiBvcGVuaWQiLCJleHAiOjE2MTM1NDQ2MzYsImlhdCI6MTYxMzU0MTAzNiwiZmFtaWx5X25hbWUiOiJEWF9hZG1pbiIsImp0aSI6IjYyNGY1OGI4LWRjMDktNDkwNS1iOGU4LWQ3YTJmYzI2NTZkNSIsImVtYWlsIjoiZGV2QG51bWVuLmZyIn0.Qg7wazJVrphuQSGeN9EosOtSeVkEeU-tGJNKZAHAGqsxxayq3d-h9R_i-TM1cK3vLRp8v0UjU32Biqc7xFa0P-tkVYESw_sLcW4YW2wC_bV0r0qVUE4h5J6GfTpv7SvAox4lpGNuM67DJ7Ar6HrIFQ4KjDEmKxBjuZ7su-Oj9zJbKI5Si9A71hNhlLzf1Vydp7nl57IGPjF-D0vAJ6Sx95VqQhPY779wGxHy4rjFtENY-1TSGi377zzLi-AiJnE1kEJX6mDD5nrBnK1txyNDDP_wIsZA1JdozyBokL-tp8_Jh6rHf0K0qpN0woIq_GDoxn5V1WZVlrR9tl6GEKDWyw&amp;expires_in=0&amp;state=NB2HI4DTHIXS6ZDPPB2HEZLFNUWXKYLUGIXG45LNMVXC443PNR2XI2LPNZZS6ZDFMNVS65LBOQZGOYZPM5ZG65LQOM======']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idd</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!loading</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>https://doxtreem-uat2.numen.solutions/deck/oauthCallback.html#access_token=eyJ4NXQiOiJNR00zTjJZeU5EVmtZalF4WXpFMU5EazROVFl6WTJNd01tWTRaalJpTlRRM04yTmhOV1ExWTJSak1HTTJaVGcwTTJWak1qQmhaVE0xTm1NellUZzNNQSIsImtpZCI6Ik1HTTNOMll5TkRWa1lqUXhZekUxTkRrNE5UWXpZMk13TW1ZNFpqUmlOVFEzTjJOaE5XUTFZMlJqTUdNMlpUZzBNMlZqTWpCaFpUTTFObU16WVRnM01BX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJEWF9hZG1pbiIsImlzcyI6Imh0dHBzOlwvXC9kb3h0cmVlbS13c28yLXVhdDIubnVtZW4uc29sdXRpb25zOjQ0M1wvb2F1dGgyXC90b2tlbiIsImdyb3VwcyI6WyJHcm91cGUtV2ViREFWIiwiSW50ZXJuYWxcL2V2ZXJ5b25lIl0sImdpdmVuX25hbWUiOiJEWF9hZG1pbiIsImF1ZCI6IlRESFlkY0hlb1ppYTZ0YXdXY29TRks3IiwidXBuIjoiRFhfYWRtaW4iLCJuYmYiOjE2MTM1NDEwMzYsImF6cCI6IlRESFlkY0hlb1ppYTZ0YXdXY29TRks3Iiwic2NvcGUiOiJpbnRlcm5hbF9sb2dpbiBvcGVuaWQiLCJleHAiOjE2MTM1NDQ2MzYsImlhdCI6MTYxMzU0MTAzNiwiZmFtaWx5X25hbWUiOiJEWF9hZG1pbiIsImp0aSI6IjYyNGY1OGI4LWRjMDktNDkwNS1iOGU4LWQ3YTJmYzI2NTZkNSIsImVtYWlsIjoiZGV2QG51bWVuLmZyIn0.Qg7wazJVrphuQSGeN9EosOtSeVkEeU-tGJNKZAHAGqsxxayq3d-h9R_i-TM1cK3vLRp8v0UjU32Biqc7xFa0P-tkVYESw_sLcW4YW2wC_bV0r0qVUE4h5J6GfTpv7SvAox4lpGNuM67DJ7Ar6HrIFQ4KjDEmKxBjuZ7su-Oj9zJbKI5Si9A71hNhlLzf1Vydp7nl57IGPjF-D0vAJ6Sx95VqQhPY779wGxHy4rjFtENY-1TSGi377zzLi-AiJnE1kEJX6mDD5nrBnK1txyNDDP_wIsZA1JdozyBokL-tp8_Jh6rHf0K0qpN0woIq_GDoxn5V1WZVlrR9tl6GEKDWyw&amp;expires_in=0&amp;state=NB2HI4DTHIXS6ZDPPB2HEZLFNUWXKYLUGIXG45LNMVXC443PNR2XI2LPNZZS6ZDFMNVS65LBOQZGOYZPM5ZG65LQOM======</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>99%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://doxtreem-uat2.numen.solutions/deck/oauthCallback.html#access_token=eyJ4NXQiOiJNR00zTjJZeU5EVmtZalF4WXpFMU5EazROVFl6WTJNd01tWTRaalJpTlRRM04yTmhOV1ExWTJSak1HTTJaVGcwTTJWak1qQmhaVE0xTm1NellUZzNNQSIsImtpZCI6Ik1HTTNOMll5TkRWa1lqUXhZekUxTkRrNE5UWXpZMk13TW1ZNFpqUmlOVFEzTjJOaE5XUTFZMlJqTUdNMlpUZzBNMlZqTWpCaFpUTTFObU16WVRnM01BX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJEWF9hZG1pbiIsImlzcyI6Imh0dHBzOlwvXC9kb3h0cmVlbS13c28yLXVhdDIubnVtZW4uc29sdXRpb25zOjQ0M1wvb2F1dGgyXC90b2tlbiIsImdyb3VwcyI6WyJHcm91cGUtV2ViREFWIiwiSW50ZXJuYWxcL2V2ZXJ5b25lIl0sImdpdmVuX25hbWUiOiJEWF9hZG1pbiIsImF1ZCI6IlRESFlkY0hlb1ppYTZ0YXdXY29TRks3IiwidXBuIjoiRFhfYWRtaW4iLCJuYmYiOjE2MTM1NDEwMzYsImF6cCI6IlRESFlkY0hlb1ppYTZ0YXdXY29TRks3Iiwic2NvcGUiOiJpbnRlcm5hbF9sb2dpbiBvcGVuaWQiLCJleHAiOjE2MTM1NDQ2MzYsImlhdCI6MTYxMzU0MTAzNiwiZmFtaWx5X25hbWUiOiJEWF9hZG1pbiIsImp0aSI6IjYyNGY1OGI4LWRjMDktNDkwNS1iOGU4LWQ3YTJmYzI2NTZkNSIsImVtYWlsIjoiZGV2QG51bWVuLmZyIn0.Qg7wazJVrphuQSGeN9EosOtSeVkEeU-tGJNKZAHAGqsxxayq3d-h9R_i-TM1cK3vLRp8v0UjU32Biqc7xFa0P-tkVYESw_sLcW4YW2wC_bV0r0qVUE4h5J6GfTpv7SvAox4lpGNuM67DJ7Ar6HrIFQ4KjDEmKxBjuZ7su-Oj9zJbKI5Si9A71hNhlLzf1Vydp7nl57IGPjF-D0vAJ6Sx95VqQhPY779wGxHy4rjFtENY-1TSGi377zzLi-AiJnE1kEJX6mDD5nrBnK1txyNDDP_wIsZA1JdozyBokL-tp8_Jh6rHf0K0qpN0woIq_GDoxn5V1WZVlrR9tl6GEKDWyw&amp;expires_in=0&amp;state=NB2HI4DTHIXS6ZDPPB2HEZLFNUWXKYLUGIXG45LNMVXC443PNR2XI2LPNZZS6ZDFMNVS65LBOQZGOYZPM5ZG65LQOM======</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idd&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='idd']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='template-module']/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
   </webElementXpaths>
</WebElementEntity>
