<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Listes_plusieur_role</name>
   <tag></tag>
   <elementGuidId>eb056d90-a294-4fe0-8c10-3ec144ab4000</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div[2]/div/mat-dialog-container/app-is-user-dialog/div[1]/mat-tab-group/div/mat-tab-body[3]/div/mat-list/mat-list-item[${index}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div[2]/div/mat-dialog-container/app-is-user-dialog/div[1]/mat-tab-group/div/mat-tab-body[3]/div/mat-list/mat-list-item[${index}]</value>
   </webElementProperties>
</WebElementEntity>
