<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>premiere_ligne_role</name>
   <tag></tag>
   <elementGuidId>c76342d8-cc98-42c6-84f2-3848a9e25075</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/div/app-is-users/div/div/mat-table</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/div/app-is-users/div/div/mat-table</value>
   </webElementProperties>
</WebElementEntity>
