<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>premiere_ligne</name>
   <tag></tag>
   <elementGuidId>e3bf17fa-b856-42ee-b938-c3bdb96f370c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/div/app-is-groups/div/div/mat-table</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/div/app-is-groups/div/div/mat-table</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/div/app-is-groups/div/div/mat-table</value>
   </webElementProperties>
</WebElementEntity>
