<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RechercheGroup_popup</name>
   <tag></tag>
   <elementGuidId>a1bd59d0-0e80-42c9-b7d7-ce758f48b024</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div[2]/div/mat-dialog-container/app-is-user-dialog/div[1]/mat-tab-group/div/mat-tab-body[2]/div/mat-list/mat-list-item[1]/div/mat-form-field/div/div[1]/div/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[2]/div/mat-dialog-container/app-is-user-dialog/div[1]/mat-tab-group/div/mat-tab-body[2]/div/mat-list/mat-list-item[1]/div/mat-form-field/div/div[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div[2]/div/mat-dialog-container/app-is-user-dialog/div[1]/mat-tab-group/div/mat-tab-body[2]/div/mat-list/mat-list-item[1]/div/mat-form-field/div/div[1]/div/input</value>
   </webElementProperties>
</WebElementEntity>
