<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RechercheRoles_popup</name>
   <tag></tag>
   <elementGuidId>89a437f1-a899-423c-9fcf-0a82874bb26d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div[2]/div/mat-dialog-container/app-is-user-dialog/div[1]/mat-tab-group/div/mat-tab-body[3]/div/mat-list/mat-list-item[1]/div/mat-form-field/div/div[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div[2]/div/mat-dialog-container/app-is-user-dialog/div[1]/mat-tab-group/div/mat-tab-body[3]/div/mat-list/mat-list-item[1]/div/mat-form-field/div/div[1]/div/input</value>
   </webElementProperties>
</WebElementEntity>
