<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Resultat</name>
   <tag></tag>
   <elementGuidId>c8bc144e-726c-4d96-ab6e-6a67d26f989f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/div/app-sg-habilitations/div/mat-drawer-container/mat-drawer/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;usertable&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;usertable&quot;]</value>
   </webElementProperties>
</WebElementEntity>
