<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Autocomplet_Groupe_proprerties</name>
   <tag></tag>
   <elementGuidId>71c5d84a-c7e6-466e-baec-7bbb0d6135af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;advanced-search-secondary-properties-base&quot;]/select-sg-type/md-autocomplete</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
