<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bloc_rechercher</name>
   <tag></tag>
   <elementGuidId>f27cfa68-145d-4b8e-9bd1-334841838c3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//md-icon[@md-svg-icon = 'mdi:information-outline' and @aria-label = 'Permet de rechercher sur le dossier courant']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;tab-content-15&quot;]/div/md-content/div/div/div[1]/md-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>md-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-svg-icon</name>
      <type>Main</type>
      <value>mdi:information-outline</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Permet de rechercher sur le dossier courant</value>
   </webElementProperties>
</WebElementEntity>
