<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bouton_sauvegarder_la_recherche</name>
   <tag></tag>
   <elementGuidId>3b648d6d-5397-4393-ae41-42dfd23007af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;search&quot;]/div[2]/md-toolbar/div/button[4]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//svg[@id='content-save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;search&quot;]/div[2]/md-toolbar/div/button[4]</value>
   </webElementProperties>
</WebElementEntity>
