<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_emplacement</name>
   <tag></tag>
   <elementGuidId>ac61d0b4-5f00-465e-9780-4f6ad20027d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//md-icon[@md-svg-src='mdi:folder-search']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>folder-search</value>
   </webElementProperties>
</WebElementEntity>
