<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click_Grp_propriete</name>
   <tag></tag>
   <elementGuidId>f86c3a1e-77fe-4d31-b9fd-de8bf6d1f41d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//md-select[@id = '${aid}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>md-select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>${aid}</value>
   </webElementProperties>
</WebElementEntity>
