<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>test_btn</name>
   <tag></tag>
   <elementGuidId>2b275cf0-2c0c-4662-96da-6528b0b9a364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[5]/div/div/div/div[2]/nav/div/div[3]/div/form/div/div/form/md-content/div[2]/md-tabs/md-tabs-content-wrapper/md-tab-content[2]/div/md-dialog-actions/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
